defaults:
  - _self_
  - streams: raw_mp4_stream
  - pipeline: ???
  - override hydra/hydra_logging: none
  - override hydra/job_logging: disabled

ray: false
prefilter: false

# Multi-worker distributed processing
world_size: 1    # Total number of workers
local_rank: 0    # Current worker rank (0 to world_size-1)

hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .
